include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

.modelzoo:
  stage: deploy

  before_script:
    - julia --project=.fluxbot -e 'using Pkg; Pkg.instantiate()'

  script:

    # if triggered by FluxBot
    - git clone https://github.com/FluxML/Flux.jl
    - cd Flux.jl && git fetch origin pull/$PRID/head:test_$PRID
    - git checkout test_$PRID
    - julia --project -e 'using Pkg;
            Pkg.instantiate();'
    - cd ..
    # end

    - export FLUX="$PWD/Flux.jl"
    - export JULIA_LOAD_PATH=".:$FLUX::"
    - julia --project -e 'using Pkg;
        Pkg.instantiate();
        Pkg.develop(PackageSpec(path = ENV["FLUX"]));
        Pkg.resolve();
        Pkg.API.precompile();'

    - cd script
    - julia --project -e 'using Pkg; Pkg.instantiate()'
    - julia --project convert.jl $TESTSUITE

  after_script:
    - apt-get install unzip
    - julia --project=.fluxbot -e 'using FluxBot; FluxBot.respond()'
  
  only:
    variables:
      - PRID
      - TESTSUITE
      - FLUXBOT
      - REPO_NAME
  artifacts:
    paths:
      - notebooks/*.ipynb

zoo:1.0:
    extends:
      - .julia:1.0
      - .modelzoo
    tags:
      - nvidia

zoo:1.1:
    extends:
      - .julia:1.1
      - .modelzoo
    tags:
      - nvidia

zoo:1.2:
    extends:
      - .julia:1.2
      - .modelzoo
    tags:
      - nvidia

zoo:1.3:
    extends:
      - .julia:1.3
      - .modelzoo
    tags:
      - nvidia

zoo:nightly:
    extends:
      - .julia:nightly
      - .modelzoo
    tags:
      - nvidia
    allow_failure: true
